### ISSUE TITLE
logging is messed up

### ISSUE THREAD

**Issue by quasarea** [microsoft/artifacts-credprovider#133]
Setting NUGET_CREDENTIALPROVIDER_LOG_PATH
```
set NUGET_CREDENTIALPROVIDER_LOG_PATH=C:\Temp\Logs
```
and then calling
```
NuGet install -NonInteractive  -Prerelease -Framework net472 -ExcludeVersion -DependencyVersion Lowest -OutputDirectory packages -Version 1.0.4 mypackage
```
throws
```
Unhandled Exception: System.UnauthorizedAccessException: Access to the path 'C:\Temp\Logs' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding)
   at System.IO.File.InternalAppendAllText(String path, String contents, Encoding encoding)
   at NuGetCredentialProvider.Logging.LoggerBase.Log(LogLevel level, String message) in E:\A\_work\207\s\CredentialProvider.Microsoft\Logging\LoggerBase.cs:line 55
   at NuGetCredentialProvider.Logging.MultiLogger.Log(LogLevel level, String message) in E:\A\_work\207\s\CredentialProvider.Microsoft\Logging\MultiLogger.cs:line 16
   at NuGetCredentialProvider.CredentialProviders.Vsts.BearerTokenProvider.GetTokenCache(ILogger logger) in E:\A\_work\207\s\CredentialProvider.Microsoft\CredentialProviders\Vsts\BearerTokenProvider.cs:line 118
   at NuGetCredentialProvider.CredentialProviders.Vsts.BearerTokenProvider..ctor(ILogger logger) in E:\A\_work\207\s\CredentialProvider.Microsoft\CredentialProviders\Vsts\BearerTokenProvider.cs:line 25
   at NuGetCredentialProvider.CredentialProviders.Vsts.VstsCredentialProvider..ctor(ILogger logger) in E:\A\_work\207\s\CredentialProvider.Microsoft\CredentialProviders\Vsts\VstsCredentialProvider.cs:line 29
   at NuGetCredentialProvider.Program.<Main>d__8.MoveNext() in E:\A\_work\207\s\CredentialProvider.Microsoft\Program.cs:line 75
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGetCredentialProvider.Program.<Main>(String[] args)
```
c:\temp exists and its writable by everyone

**Comment by jmyersmsft** [comment]
`NUGET_CREDENTIALPROVIDER_LOG_PATH` names a file, not a folder. Setting it to an existing folder will result in that exception.
