### ISSUE TITLE
ErrorCode: integrated_windows_auth_not_supported_managed_user

### ISSUE THREAD

**Issue by Fabian-Schmidt** [microsoft/artifacts-credprovider#194]
I am trying to use the credential provider from PowerShell via the Package Management Cmdlets. The authentication keeps failing and it generates personal access token with `vso.drop_write` scope for every attempt.

Repro Steps:
1. Install credential manager via provided PowerShell
2. Register my Azure Artifacts provider
3. Find package 
```PowerShell
./installcredprovider.ps1
Register-PackageSource -Name $artifactFeedName -Location $artifactFeed -ProviderName NuGet -SkipValidate
Find-Package -Name $artifactName -Source $artifactFeedName
```

Error Message is repeated.
After every attempt to sign in it creates a new personal access token and fails.
```
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenIWAHandler.PreTokenRequestAsync()
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenHandlerBase.RunAsync()
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.AcquireTokenCommonAsync(String resource, String clientId, IntegratedWindowsAuthInput iwaInput)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContextIntegratedAuthExtensions.AcquireTokenAsync(AuthenticationContext ctx, String resource, String clientId, UserCredential userCredential)
   at NuGetCredentialProvider.CredentialProviders.Vsts.AdalTokenProvider.AcquireTokenWithWindowsIntegratedAuth(CancellationToken cancellationToken) in E:\A\_work\911\s\CredentialProvider.Microsoft\CredentialProviders\Vsts\AdalTokenProvider.cs:line 122
   at NuGetCredentialProvider.CredentialProviders.Vsts.WindowsIntegratedAuthBearerTokenProvider.GetTokenAsync(Uri uri, CancellationToken cancellationToken) in E:\A\_work\911\s\CredentialProvider.Microsoft\CredentialProviders\Vsts\BearerTokenProviders.cs:line 58
   at NuGetCredentialProvider.CredentialProviders.Vsts.VstsCredentialProvider.HandleRequestAsync(GetAuthenticationCredentialsRequest request, CancellationToken cancellationToken) in E:\A\_work\911\s\CredentialProvider.Microsoft\CredentialProviders\Vsts\VstsCredentialProvider.cs:line 117
        ErrorCode: integrated_windows_auth_not_supported_managed_user
[Minimal] [CredentialProvider]DeviceFlow: https://pkgs.dev.azure.com/contoso/<UID>/_packaging/<UID>@<UID>/nuget/v3/registrations2-semver2/<packageName>/index.json
[Minimal] [CredentialProvider]ATTENTION: User interaction required.

    **********************************************************************

    To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code HMKX9YF4Y to authenticate.

    **********************************************************************
```

# System details
Windows 10 Version 2004
Credential Provider Version: `0.1.23.0`
PackageManagement Module Version `1.4.7`
Package Provider NuGet Version `3.0.0.1` 

My Azure AD account is cloud only. Also the account is a guest in the target tenant of Azure DevOps instance.

**Comment by satbai** [comment]
The way the credential provider works is that it first tries Windows integrated auth and if that doesn't work it'll fall back to interactive auth. In your case it's device flow. Just to clarify, did you try following the device flow instructions to authenticate interactively? Did that fail too?

**Comment by Fabian-Schmidt** [comment]
When I finish the device flow the module creates a personal access token in Azure DevOps and then the same error is repeated and it ask me again for device flow. This results in yet another personal access token being created by the module.

**Comment by gintuoklis** [comment]
Hey Guys, 
Was this issue solved. I'm experiencing the same problem as well.

**Comment by AlexVTor** [comment]
Hello,
I have looked into this issue once again and have tried to reproduce it locally after following your steps and set up. After testing with a newer nuget version, I haven't been able to reproduce it. If you have any more information you would like to provide, or if the issue persists after updating to a newer version of nuget, feel free to reach out. Until then this issue will remain closed, thanks!
