### ISSUE TITLE
Having to set NUGET_CREDENTIALPROVIDER_MSAL_ENABLED to authenticate

### ISSUE THREAD

**Issue by nathansoz** [microsoft/artifacts-credprovider#233]
The credential provider has been working fine for me up until today. Today I started to get a 401 when running `dotnet restore --interactive` with no changes in feed permissions. Setting NUGET_CREDENTIALPROVIDER_MSAL_ENABLED has unblocked my restore, but it seems like something has regressed. Should MSAL be enabled by default or is there a way we can give a hint to the provider without everyone on my team having to set an environment variable?

**Comment by kartelan** [comment]
I was hitting this yesterday as well. I saw the following exception in Credential Provider Log:
```
06:53:39.240 19074 Verbose] VstsCredentialProvider - Bearer token provider 'ADAL Device Code' failed with exception:\nMicrosoft.IdentityModel.Clients.ActiveDirectory.AdalServiceException: AADSTS50097: Device authentication is required.
Trace ID: bf61f3c3-637a-482e-9230-6e5b50b81a01
Correlation ID: 7524041d-537f-479c-8032-375df82771d0
Timestamp: 2021-01-20 06:53:39Z
 ---> Microsoft.IdentityModel.Clients.ActiveDirectory.AdalServiceException: Response status code does not indicate success: 401 (Unauthorized).
   at Microsoft.Identity.Core.OAuth2.OAuthClient.GetResponseAsync[T](Boolean respondToDeviceAuthChallenge)
    ErrorCode: Unauthorized
    StatusCode: 401
   --- End of inner exception stack trace ---
   at Microsoft.Identity.Core.OAuth2.OAuthClient.GetResponseAsync[T](Boolean respondToDeviceAuthChallenge)
   at Microsoft.Identity.Core.OAuth2.OAuthClient.GetResponseAsync[T]()
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenHandlerBase.SendHttpMessageAsync(IRequestParameters requestParameters)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenHandlerBase.SendTokenRequestAsync()
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenByDeviceCodeHandler.SendTokenRequestAsync()
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenHandlerBase.CheckAndAcquireTokenUsingBrokerAsync()
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenHandlerBase.RunAsync()
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.AcquireTokenByDeviceCodeAsync(DeviceCodeResult deviceCodeResult, CancellationToken cancellationToken)
   at NuGetCredentialProvider.CredentialProviders.Vsts.AdalTokenProvider.AcquireTokenWithDeviceFlowAsync(Func`2 deviceCodeHandler, CancellationToken cancellationToken, ILogger logger)
   at NuGetCredentialProvider.CredentialProviders.Vsts.DeviceCodeFlowBearerTokenProvider.GetTokenAsync(Uri uri, CancellationToken cancellationToken)
   at NuGetCredentialProvider.CredentialProviders.Vsts.VstsCredentialProvider.HandleRequestAsync(GetAuthenticationCredentialsRequest request, CancellationToken cancellationToken)
    ErrorCode: invalid_grant
    StatusCode: 401
```

Setting NUGET_CREDENTIALPROVIDER_MSAL_ENABLED helped met get past the issue.

**Comment by nathansoz** [comment]
Setting the environment variable is fine as a temporary workaround, but in general if this is going to remain feature flagged it would be great to have a way to enable this feature via some configuration we can store in our repos. I

**Comment by reynoldsa** [comment]
Agreed with @nathansoz on this. This behaviour resulted in my dev box builds appearing to break suddenly, and it's not obvious that setting this environment variable is the way to fix it. A way to set it via the repo, or an error message at the least, would be helpful in reducing time lost for others to come.

**Comment by johnterickson** [comment]
See internal ICM 224085642

**Comment by johnterickson** [comment]
Note to others the env var must be set to `true` not `1`:
```
NUGET_CREDENTIALPROVIDER_MSAL_ENABLED=true
```

**Comment by johnterickson** [comment]
@reynoldsa an AAD server-side fix is ETA Feb 5 and then things will be back to normal

**Comment by johnterickson** [comment]
Hotfix rollout is in progress.
