### ISSUE TITLE
Race hazards in token on Linux - Exception generated (Wait operations not supported on this platform)

### ISSUE THREAD

**Issue by rgammans** [microsoft/artifacts-credprovider#259]
Using this via artifacts-keyrings, pipenv when authenticated fails with the following (.net) exeception.

```
Unhandled exception. System.PlatformNotSupportedException: Wait operations on multiple wait handles including a named synchronization primitive are not supported on this platform.
   at System.Threading.WaitHandle.WaitMultipleIgnoringSyncContext(IntPtr* waitHandles, Int32 numHandles, Boolean waitAll, Int32 millisecondsTimeout)
   at System.Threading.WaitHandle.WaitMultiple(ReadOnlySpan`1 waitHandles, Boolean waitAll, Int32 millisecondsTimeout)
   at System.Threading.WaitHandle.WaitMultiple(WaitHandle[] waitHandles, Boolean waitAll, Int32 millisecondsTimeout)
   at System.Threading.WaitHandle.WaitAny(WaitHandle[] waitHandles, Int32 millisecondsTimeout)
   at NuGetCredentialProvider.Util.SessionTokenCache.get_Cache()
   at NuGetCredentialProvider.Util.SessionTokenCache.TryGetValue(Uri key, String& value)
   at NuGetCredentialProvider.RequestHandlers.GetAuthenticationCredentialsRequestHandler.TryCache(GetAuthenticationCredentialsRequest request, String& cachedToken)
   at NuGetCredentialProvider.RequestHandlers.GetAuthenticationCredentialsRequestHandler.HandleRequestAsync(GetAuthenticationCredentialsRequest request)
   at NuGetCredentialProvider.Program.Main(String[] args)
   at NuGetCredentialProvider.Program.<Main>(String[] args)
WARNING: Keyring is skipped due to an exception: Failed to get credentials: process with PID 24324 exited with code -6; additional error message:

```

I believe this line is the cause of this exception; as forcing sequential install fixes the issue.
https://github.com/microsoft/artifacts-credprovider/blob/28e6976481a68e131c55275dd4a51dd54d120b3f/CredentialProvider.Microsoft/Util/SessionTokenCache.cs#L46

**Comment by rgammans** [comment]
I should have said this is on Linux (debian buster) with the Microsoft dotnet-sdk-5.0 package

**Comment by ggirard07** [comment]
@rgammans Good luck getting this seen and fixed by using the Developer Community!

**Comment by rgammans** [comment]
Dev community link
https://developercommunity.visualstudio.com/t/Race-hazards-in-token-on-Linux---Excepti/1442296?space=8&viewtype=all
