### ISSUE TITLE
Windows Integrated Auth fails 

### ISSUE THREAD

**Issue by prochnowc** [Microsoft/artifacts-credprovider#41]
All our users are not able to authenticate with our DevOps Artifacts feed.

```
[Verbose] [CredentialProvider]GET https://XXX
[Verbose] [CredentialProvider]Could not find AAD authority from headers, using default: https://login.microsoftonline.com
[Verbose] [CredentialProvider]Using AAD authority: https://login.microsoftonline.com/common
[Verbose] [CredentialProvider]Failed to acquire token from cache
[Verbose] [CredentialProvider]VstsCredentialProvider - Exception trying to generate VSTS/TFS token: https://XXX, message: password_required_for_managed_user: Password is required for managed user, stack:    at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenNonInteractiveHandler.PreTokenRequestAsync()
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenHandlerBase.RunAsync()
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.AcquireTokenCommonAsync(String resource, String clientId, UserCredential userCredential)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContextIntegratedAuthExtensions.AcquireTokenAsync(AuthenticationContext ctx, String resource, String clientId, UserCredential userCredential)
   at NuGetCredentialProvider.CredentialProviders.Vsts.AdalTokenProvider.AcquireTokenWithWindowsIntegratedAuth(CancellationToken cancellationToken) in E:\A\_work\203\s\CredentialProvider.Microsoft\CredentialProviders\Vsts\AdalTokenProvider.cs:line 98
   at NuGetCredentialProvider.CredentialProviders.Vsts.BearerTokenProvider.GetAsync(Uri uri, Boolean isRetry, Boolean isNonInteractive, Boolean canShowDialog, CancellationToken cancellationToken) in E:\A\_work\203\s\CredentialProvider.Microsoft\CredentialProviders\Vsts\BearerTokenProvider.cs:line 65
   at NuGetCredentialProvider.CredentialProviders.Vsts.VstsCredentialProvider.HandleRequestAsync(GetAuthenticationCredentialsRequest request, CancellationToken cancellationToken) in E:\A\_work\203\s\CredentialProvider.Microsoft\CredentialProviders\Vsts\VstsCredentialProvider.cs:line 70
[Verbose] [CredentialProvider]VstsCredentialProvider - Could not find credentials for https://XXX
[Information] [CredentialProvider]Username:
[Information] [CredentialProvider]Password:
```

**Comment by zarenner** [comment]
Hi Christian.

Sorry about this issue - there's indeed a bug in 0.1.7 where if WIA fails unexpectedly, it doesn't attempt to use other mechanisms (e.g. device code flow). I've fixed this as well as another issue in a PR that I plan to merge within the next couple days after some more testing. Until then, I'd recommend jumping back to 0.1.6 which doesn't have WIA, as a workaround.

For my understanding / to make sure there isn't another bug, did you expect WIA to succeed? e.g. are you attempting to log into an AAD-backed Azure DevOps organization using a domain account?

**Comment by zarenner** [comment]
I've released https://github.com/Microsoft/artifacts-credprovider/releases/tag/0.1.8 which should resolve this issue. Please give it a try and let me know if it's resolved for you.

**Comment by prochnowc** [comment]
We will give it a try. Thanks!

**Comment by satbai** [comment]
Closing the issue because there's no activity after @zarenner's fix.
