### ISSUE TITLE
Azure Artifacts Credential provider failing to start

### ISSUE THREAD

**Issue by vickyen** [microsoft/artifacts-credprovider#454]
Hi, I'm seeing an issue where Azure Artifacts credential provider is failing to start and timing out. Previously, the timeout was set to 5s and was increased to 60s, but we are still seeing this issue.

Has anyone seen this before?

Here's the stack trace:
Using d:\os\tools\CredentialProvider\CredentialProvider.Microsoft\CredentialProvider.Microsoft.exe as a credential provider plugin.
Problem starting the plugin 'd:\os\tools\CredentialProvider\CredentialProvider.Microsoft\CredentialProvider.Microsoft.exe'. Plugin 'CredentialProvider.Microsoft' failed within 60.070 seconds with exit code -1.
NuGet.Protocol.Plugins.PluginException: Plugin 'CredentialProvider.Microsoft' failed within 60.070 seconds with exit code -1. ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.Plugins.MessageDispatcher.<DispatchWithNewContextAsync>d__29`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.Plugins.SymmetricHandshake.<HandshakeAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.Plugins.Connection.<ConnectAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.Plugins.PluginFactory.<CreatePluginAsync>d__7.MoveNext()
   --- End of inner exception stack trace ---
   at NuGet.Protocol.Plugins.PluginFactory.<CreatePluginAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.Plugins.PluginFactory.<GetOrCreateAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.Plugins.PluginManager.<TryCreatePluginAsync>d__22.MoveNext()
Problem starting the plugin 'd:\os\tools\CredentialProvider\CredentialProvider.Microsoft\CredentialProvider.Microsoft.exe'. Plugin 'CredentialProvider.Microsoft' failed within 60.070 seconds with exit code -1.
  Plugin 'CredentialProvider.Microsoft' failed within 60.070 seconds with exit code -1.
  A task was canceled.

**Comment by embetten** [comment]
@vickyen is the credential provider in the correct location on your machine? See the install location by Os in [this section of our ReadMe](https://github.com/microsoft/artifacts-credprovider#manual-installation-on-windows). From the error message, it looks like nuget.exe is failing to find or start the plugin at all. Furthermore, can you make sure you have the latest version of the credential provider installed and please let me know if it was working before.

**Comment by vickyen** [comment]
yes, I've checked that the credential provider is in the location its trying to invoke from. I have also verified that the version is the latest 1.0.0.0

**Comment by embetten** [comment]
The latest version is [1.0.9](https://github.com/microsoft/artifacts-credprovider/releases/tag/v1.0.9). And does this occur in a pipeline or locally? On what OS?

**Comment by vickyen** [comment]
This occurs on machines we use to build Windows, which have Windows OS. I've updated the credential provider to version 1.0.9 and will see if it helps

**Comment by embetten** [comment]
could be related (or the same as) #192
