### ISSUE TITLE
Corrupted 'SessionTokenCache.dat' produces inactionable, unrecoverable 'The data is invalid' errors

### ISSUE THREAD

**Issue by bergbria** [Microsoft/artifacts-credprovider#46]
## Overview
I installed the cred provider to interact with an Azure DevOps packages feed. All was well.

At some point (possibly after a Blue Screen, though I'm not sure), all of my nuget commands started failing with the following error message.
```Terminating plugin 'CredentialProvider.Microsoft' due to an unrecoverable fault:  NuGet.Protocol.Plugins.ProtocolException: A plugin protocol exception occurred. ---> NuGet.Protocol.Plugins.ProtocolException: The data is invalid.

   at NuGet.Protocol.Plugins.OutboundRequestContext`1.HandleFault(Message fault)
   at NuGet.Protocol.Plugins.MessageDispatcher.OnMessageReceived(Object sender, MessageEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at NuGet.Protocol.Plugins.StandardOutputReceiver.OnLineRead(Object sender, LineReadEventArgs e)
   --- End of inner exception stack trace ---
```

The error didn't go away after re-runs and a reboot.
The errors provided no hint as to what the issue was or how it could be resolved.

After debugging for a while, I was able to trace the error to the following call stack:
```>	System.Security.dll!System.Security.Cryptography.ProtectedData.Unprotect(byte[], byte[], System.Security.Cryptography.DataProtectionScope)	Unknown
 	credentialprovider.microsoft.exe!NuGetCredentialProvider.Util.EncryptedFile.ReadFileBytes(string, bool) Line 17	C#
 	credentialprovider.microsoft.exe!NuGetCredentialProvider.Util.SessionTokenCache.ReadFileBytes() Line 85	C#
 	credentialprovider.microsoft.exe!NuGetCredentialProvider.Util.SessionTokenCache.Cache.get() Line 27	C#
 	credentialprovider.microsoft.exe!NuGetCredentialProvider.Util.SessionTokenCache.TryGetValue(System.Uri, out string) Line 53	C#
 	credentialprovider.microsoft.exe!NuGetCredentialProvider.RequestHandlers.GetAuthenticationCredentialsRequestHandler.TryCache(NuGet.Protocol.Plugins.GetAuthenticationCredentialsRequest, out string) Line 149	C#
 	credentialprovider.microsoft.exe!NuGetCredentialProvider.RequestHandlers.GetAuthenticationCredentialsRequestHandler.HandleRequestAsync(NuGet.Protocol.Plugins.GetAuthenticationCredentialsRequest) Line 63	C#
 	credentialprovider.microsoft.exe!NuGetCredentialProvider.Program.Main(string[]) Line 155	C#
```

It looks like my %LocalAppData%\MicrosoftCredentialProvider\SessionTokenCache.dat file was corrupted somehow, leading to these errors.

## Repro
1. Use the cred provider to install a package
2. Use a text editor to tweak the contents of %LocalAppData%\MicrosoftCredentialProvider\SessionTokenCache.dat
3. Try to install another package using the cred provider

## Expected behavior

The tool should ideally detect that the file is corrupted and recreate it. That failing, it should at least log something like 'File X contains invalid data.'

**Comment by salvmd** [comment]
@bergbria,thank you for debugging this and providing the repro steps!
I've logged a bug to improve the error handling when reading invalid SessionTokenCache.dat files. I'll post back once we have it fixed
