### ISSUE TITLE
Cred provider does not work with .net sdk 3.0.100

### ISSUE THREAD

**Issue by shubham90** [microsoft/artifacts-credprovider#51]
Install .net sdk 3.0.100.

Set NUGET_PLUGINS_PATH to point to the cred provider location. Use dotnet restore to restore packages. Fails with:

It was not possible to find any compatible framework version
The specified framework 'Microsoft.NETCore.App', version '2.1.0' was not found.
  - Check application dependencies and target a framework version installed at:
      /usr/share/dotnet/
  - Installing .NET Core prerequisites might help resolve this problem:
      https://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
  - The .NET Core framework and SDK can be installed from:
      https://aka.ms/dotnet-download
  - The following versions are installed:
      3.0.0-preview-27122-01 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]
     1>/usr/share/dotnet/sdk/3.0.100-preview-009812/NuGet.targets(114,5): error : Broken pipe [/root/code/code1/code1.csproj]
         System.IO.IOException: Broken pipe
            at System.IO.FileStream.WriteNative(ReadOnlySpan`1 source)
            at System.IO.FileStream.FlushWriteBuffer()
            at System.IO.FileStream.Dispose(Boolean disposing)
            at System.IO.Stream.Close()
            at System.IO.StreamWriter.CloseStreamFromDispose(Boolean disposing)
            at System.IO.StreamWriter.Dispose(Boolean disposing)
            at System.IO.TextWriter.Dispose()
            at NuGet.Protocol.Plugins.Sender.Dispose()
            at NuGet.Protocol.Plugins.Connection.Dispose()
            at NuGet.Protocol.Plugins.Plugin.Dispose()
            at NuGet.Protocol.Plugins.PluginFactory.CreatePluginAsync(String filePath, IEnumerable`1 arguments, IRequestHandlers requestHandlers, ConnectionOptions options, CancellationToken sessionCancellationToken)
            at NuGet.Protocol.Plugins.PluginFactory.GetOrCreateAsync(String filePath, IEnumerable`1 arguments, IRequestHandlers requestHandlers, ConnectionOptions options, CancellationToken sessionCancellationToken)
            at NuGet.Protocol.Core.Types.PluginManager.<>c__DisplayClass24_0.<<TryCreatePluginAsync>b__0>d.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---

After that I removed the NUGET_PLUGINS_PATH location and it worked well. So, there is something wrong with nuget talking to plugin for the first time.

Need to revert [this ](https://github.com/dotnet/dotnet-docker/pull/891/commits/b60953809a4b0fd37e5d9412eb1bcd10741873a4)commit once resolved.

**Comment by zarenner** [comment]
@shubham90 can this be closed now that https://github.com/microsoft/artifacts-credprovider/issues/112 is resolved (.NET Core major-version rollforward is enabled in the runsettings)?

**Comment by shubham90** [comment]
sure, thanks for fixing this.
